### ISSUE TITLE
Segmentation fault on `cutest_cfn_`

### ISSUE THREAD

**Issue by abelsiqueira** [optimizers/CUTEst.jl#1]
Tried testing the package, but got a segmentation fault.
Downloaded NPL, and did
````
julia> Pkg.clone(pwd())
julia> Pkg.build("NLP.jl")
````
Download CUTEst.jl and did inside of folder test
````
$ LD_LIBRARY_PATH=. julia
julia> include("../src/CUTEst.jl")
julia> include("test_cutest.jl")
````
Output: https://gist.github.com/abelsiqueira/211d9df07e61926671e7

**Comment by dpo** [comment]
Thanks for the report. I've only tested OSX. The problem is probably with the way the shared lib is built. I'll try to test on a Linux machine soon.

**Comment by dpo** [comment]
What happens if you change [this line](https://github.com/optimizers/CUTEst.jl/blob/master/src/CUTEst.jl#L51) to use `ld -shared` instead of `gfortran -shared`?

**Comment by abelsiqueira** [comment]
If I change only that it gives a lookup error: `undefined symbol _gfortran_st_open`, but when I add `-lgfortran` to the end, the same error happens (only the `ip: xxxxxx` changes to another numbers).

**Comment by dpo** [comment]
It works well for me on CentOS if I build the shared CUTEst library with the Homebrew formula. I had to go hardcode the path to `libcutest` in `CUTEst.jl` even though the path is on my `LD_LIBRARY_PATH`. I'm not sure if this is CentOS-specific or not.

**Comment by abelsiqueira** [comment]
It looks like the brew is working on linux, except for copying the to /usr/local/lib. The default command really shouln't be able to, since it had no sudo.
Should there be a separate command? Since things are installed to $HOME/.linuxbrew, running brew with sudo should not be the case.

After installing the library with the brew, your package worked. I will continue/start the transition now.

**Comment by dpo** [comment]
Linuxbrew is never run with `sudo`, instead users add `~/.linuxbrew/bin` to their `LD_LIBRARY_PATH`. Thanks for checking!

**Comment by abelsiqueira** [comment]
Closing this, as it is a problem with my library, and now I'm using your version.
