### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dpo** [optimizers/CUTEst.jl#32]
Just a thought. I wonder if the documentation for the core interface functions could be the contents of the corresponding man page. For example `help(usetup)` would display the result of `man cutest_usetup`. Is that possible?

**Comment by abelsiqueira** [comment]
Since the man pages are in `$CUTEST/man/man3`, this will be very easy to add to the script. I started to read the Docile and Lexicon documentation, so I'll implement this soon.

**Comment by dpo** [comment]
Great! Thanks!

**Comment by abelsiqueira** [comment]
Converting the man page to plain text was a little more troublesome than anticipated, if you know of a better way, please let me know. f1950c8d shows what I managed to do.

**Comment by dpo** [comment]
I thought it might be possible to set the contents of a docstring to the result of the command `man cutest_usetup`.

**Comment by dpo** [comment]
For example at the Julia command line, I can hit `;` and do
```JULIA
shell> man cutest_usetup
```
Could we get `help(usetup)` to perform the same operation?

**Comment by abelsiqueira** [comment]
I will check if that's possible, but we need to consider the documentation for the specialized interface too, because they share the name now.

**Comment by abelsiqueira** [comment]
The best I could reach was
````
@doc :(run(`man ls`)) foo
````
But I can't run that. Do you think we should ask in julia-users?

**Comment by dpo** [comment]
Maybe it's not possible. Perhaps the docstring could just recommend that the user run the shell command `man cutest_$(function_name)` to learn more.

**Comment by abelsiqueira** [comment]
That's good

**Comment by abelsiqueira** [comment]
I implemented your suggestion along with a basic usage and parameter list in f82c0e54.
I will try to grab some info from the man file from python before _PRing_.

**Comment by abelsiqueira** [comment]
Implemented by #36
