### ISSUE TITLE
Should `hess` return only the upper triangular part?

### ISSUE THREAD

**Issue by abelsiqueira** [optimizers/CUTEst.jl#6]
The function `hess` from the `julia_interface.jl` is currently returning a sparse upper triangular matrix, because it is symmetric. But since this interface should be easier to use, wouldn't it be better to return a matrx with both sides filled? This will (almost) double allocation, but will enable very high level code, like
````
hess(nlp, x)\v
````

**Comment by dpo** [comment]
Yes it would definitely be better, at least until there is support for symmetric sparse matrices in Julia.

**Comment by abelsiqueira** [comment]
Implemented in abelsiqueira@72b5728

**Comment by dpo** [comment]
Would you like me to cherry-pick those specific commits, or do you want to submit targeted pull requests for them?
